name: 'Backport pull request'
description: 'Backport pull request based on backport label'
branding:
  icon: corner-left-down
  color: gray-dark
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
