#!/bin/bash
set -e
set -o pipefail

backport() {
  local number=$1
  local branch=$2
  local git_user_email=$3
  local git_user_name=$4

  local repository=$(jq --raw-output .repository.clone_url "$GITHUB_EVENT_PATH")
  local backport_branch="backport/${number}-to-${branch}"
  local merge_sha=$(jq --raw-output .pull_request.merge_commit_sha "$GITHUB_EVENT_PATH")

  local workdir=$(mktemp -d)
  git config --global user.email "${git_user_email}"
  git config --global user.name "${git_user_name}"

  git clone --no-tags -b ${branch} ${repository} "${workdir}"
  (cd "${workdir}";
  # so we don't log the access token by accident
  git config 'http.https://github.com/.extraheader' "Authorization: Bearer ***"
  sed -i -e "s/\*\*\*/${GITHUB_TOKEN}/" .git/config
  git checkout -b ${backport_branch};
  git cherry-pick --mainline 1 ${merge_sha};
  git push --set-upstream origin ${backport_branch};
  rm -rf "${workdir}")

  local title=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
  local pull_request_title="[Backport ${branch}] ${title}"
  local pull_request_body="Backport of #${number}"
  local pull_request="{\
    \"title\": \"${pull_request_title}\", \
    \"body\": \"${pull_request_body}\", \
    \"head\": \"${backport_branch}\", \
    \"base\": \"${branch}\" \
  }"

  local pulls=$(tmp=$(jq --raw-output .repository.pulls_url "$GITHUB_EVENT_PATH"); echo "${tmp%{*}")

  curl -XPOST -fsSL \
    -H 'Accept: application/vnd.github.v3+json' \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "${pull_request}" \
    ${pulls}
}

main() {
  local git_user_email=$1
  local git_user_name=$2

  local number=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
  local merged=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")
  local labels=$(jq --raw-output .pull_request.labels[].name "$GITHUB_EVENT_PATH")

  if [[ "$merged" != "true" ]]; then
    exit 0
  fi

  IFS=$'\n'
  for label in ${labels}; do
    if [[ "${label}" == 'backport '* ]]; then
      local branch=${label#* }
      backport ${number} ${branch} "${git_user_email}" "${git_user_name}"
    fi
  done

}

main "$@"
