name: Backport

on:
  label:
    types:
      - created
      - deleted
      - edited

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: backport
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(context);
