name: Backport

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Backport closed pull request
      id: backport
      if: github.event.pull_request.merged
      uses: ./github/actions/backport
