name: Backport

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Backport closed pull request
    if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    - uses: zregvart/backport-action@master
    - uses: mxschmitt/action-tmate@v1
