name: CI

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Backport
      if: github.event.body.merged_at != 0
      run: echo $GITHUB_SHA $GITHUB_REF
    - uses: actions/github-script@0.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(context)
