name: Backport

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: backport
      if: github.event.pull_request.merged && startsWith(github.event.pull_request.labels.*.name, 'backport ')
      run: |
        echo hi!
